---
title: "ELGAN3 MRI Radiological Read Wrangling"
author: "Meaghan Perdue"
date: "8/20/2026"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(fuzzyjoin)
```

## Read and clean-up MRI Radiological Read data for ELGAN3 subjects

```{r read data}
base_path<-"/Volumes/LaCie/Projects/elgan_dti/data"

dti<-read.csv(file.path(base_path, "afq_include.csv"))

raw <- read.csv(file.path(base_path, "elgan3_mri_radiolread.csv"))

mri <- raw %>%
  filter(
    if_any(
      -id,
      ~ coalesce(trimws(as.character(.)), "") != ""
    )
  )

# Check for duplicate IDs
dup_ids <- mri %>%
            count(id) %>%
            filter(n > 1)
print(dup_ids)

## Note - this data is indexed by family ID not subject, ID, so there are duplicates! Need to get a re-export to confirm data. For now, doing a quick look at how many subjects have abnormalities, ignoring who is who







```

## Count abnormal MRI findings

```{r count}
# Create a new variable to indicate whether ANY abnormalities were indicated

## first, reindex variables graded as 1=none, 2=mild, etc. to 0=none:

mri <- mri %>%
  mutate(across(
    c(MRICSFVSLVRi, MRICSFVSLVLe, MRICSFVS3rdV, MRICSFVS4thV,
      MRICSFSSACRi, MRICSFSSACLe, MRICSFSSPCRi, MRICSFSSPCLe,
      MRICSFSSPFRi, MRICSFSSPFLe),
    ~ replace(.x, .x == 1, 0)
  ))

## then create new variable where any value of 1 across the row results in 1 for 'abnormality'

mri <- mri %>%
  mutate(
    mri_abnorm_any = as.integer(
      rowSums(across(-id) > 0, na.rm = TRUE) > 0
    )
  )

## Check N with any abnormality
sum(mri$mri_abnorm_any)

# filter down to dataset of participants with some abnormality plus duplicate IDs

abn <- mri %>%
          filter(mri_abnorm_any > 0) %>%
          distinct()

# Check for duplicate IDs in abn subset
dup_ids_abn <- abn %>%
            count(id) %>%
            filter(n > 1)
print(dup_ids_abn)

dti_abn <- fuzzy_inner_join(
  abn, dti,
  by = "id",
  match_fun = function(x, y) str_detect(y, fixed(x))
) 

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
